apiVersion: v1
kind: ConfigMap
metadata:
  name: shiftpod-manager-config
  namespace: shiftpod-system
data:
  log-level: "info"
  grpc-port: "9090"
  metrics-port: "8080"
  checkpoint-dir: "/var/lib/shiftpod/checkpoints"
  unix-socket-path: "/var/run/shiftpod/manager.sock"
  unix-socket-permissions: "0660"
