---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: shiftpod-manager
  namespace: kube-system
  labels:
    app: shiftpod-manager
spec:
  selector:
    matchLabels:
      app: shiftpod-manager
  template:
    metadata:
      labels:
        app: shiftpod-manager
    spec:
      serviceAccountName: shiftpod-manager
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: manager
          image: shiftpod/manager:latest
          imagePullPolicy: Never
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CHECKPOINT_DIR
              value: "/var/lib/shiftpod/checkpoints"
            - name: SOCKET_PATH
              value: "/var/run/shiftpod/manager.sock"
            - name: GRPC_PORT
              value: "9090"
            - name: RUST_LOG
              value: "debug"
          ports:
            - containerPort: 9090
              name: grpc
              hostPort: 9090
          volumeMounts:
            - name: checkpoint-storage
              mountPath: /var/lib/shiftpod/checkpoints
            - name: socket-dir
              mountPath: /var/run/shiftpod
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
      volumes:
        - name: checkpoint-storage
          hostPath:
            path: /var/lib/shiftpod/checkpoints
            type: DirectoryOrCreate
        - name: socket-dir
          hostPath:
            path: /var/run/shiftpod
            type: DirectoryOrCreate
