apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd.yaml
  - rbac.yaml
  - daemonset.yaml
  - service.yaml

labels:
  - pairs:
      app: shiftpod-manager

namespace: kube-system

images:
  - name: shiftpod/manager
    newTag: latest
