---
apiVersion: v1
kind: Service
metadata:
  name: shiftpod-manager-grpc
  namespace: shiftpod-system
  labels:
    app.kubernetes.io/name: shiftpod-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: shiftpod
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
  publishNotReadyAddresses: true
