---
apiVersion: v1
kind: Service
metadata:
  name: shiftpod-manager
  namespace: kube-system
  labels:
    app: shiftpod-manager
spec:
  type: ClusterIP
  selector:
    app: shiftpod-manager
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
