version: '3'

vars:
  PROJECT_NAME: shiftpod
  BINARY_NAME: containerd-shim-shiftpod-v2
  BUILD_DIR: build
  CMD_DIR: cmd/shim

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - go clean -cache

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build the containerd shim binary
    deps: [deps]
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./{{.CMD_DIR}}
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  check:
    desc: Run all checks (fmt, vet, lint, test)
    deps: [fmt, vet, lint, test]
  
  k3d:build:
    desc: Build custom image to run k3s with criu
    deps: [build]
    cmds:
      - docker build -f ./k3s/Dockerfile.k3s-criu -t shiftpod/k3s-criu:1.32.3 .

  k3d:create:
    desc: Create K3D cluster
    cmds:
      - |
        k3d cluster create shift-cluster \
        --image shiftpod/k3s-criu:1.32.3 \
        --servers 1 --agents 1 \

  k3d:test_1:
    desc: Apply pod test 1
    cmds: 
      - kubectl apply -f ./k3s/runtimeclass.yaml
      - kubectl apply -f ./k3s/testpod.yaml

  k3d:events:
    desc: Get cluster events
    cmds:
      - kubectl get events --sort-by=.metadata.creationTimestamp

  shim:logs:
    desc: Get shim logs from k3d
    cmds:
      - docker exec k3d-shift-cluster-agent-0 cat /tmp/shiftpod.log