version: '3'

vars:
  PROJECT_NAME: shiftpod
  BINARY_NAME: containerd-shim-shiftpod-v2
  BUILD_DIR: build
  CMD_DIR: cmd/shim

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - go clean -cache

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build the containerd shim binary
    deps: [deps]
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./{{.CMD_DIR}}
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  install:
    desc: Install the shim binary to system path
    deps: [build]
    cmds:
      - sudo scp ./{{.BUILD_DIR}}/{{.BINARY_NAME}} kelvinc@192.168.0.235:/home/kelvinc/shiftpod
      - sha256sum ./{{.BUILD_DIR}}/{{.BINARY_NAME}}

  check:
    desc: Run all checks (fmt, vet, lint, test)
    deps: [fmt, vet, lint, test]
  
  k3d:create:
    desc: Create K3D cluster
    cmds:
      - k3d cluster create shift-cluster \
        --servers 1 --agents 1 \
        --volume "$(realpath ./k3s/config.toml.tmpl)":/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl@all \
        --volume "$(realpath ./build/containerd-shim-shiftpod-v2)":/usr/local/bin/containerd-shim-shiftpod-v2@all

