apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
      annotations:
        shiftpod/enable-checkpoint: "true"
    spec:
      runtimeClassName: shiftpod-class
      containers:
        - image: kelvin/counter:latest
          name: counter
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 128Mi