// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/manager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerService_NotifyCheckpoint_FullMethodName        = "/shiftpod.manager.v1.ManagerService/NotifyCheckpoint"
	ManagerService_RequestMigrationRestore_FullMethodName = "/shiftpod.manager.v1.ManagerService/RequestMigrationRestore"
	ManagerService_PullImage_FullMethodName               = "/shiftpod.manager.v1.ManagerService/PullImage"
	ManagerService_FinishRestore_FullMethodName           = "/shiftpod.manager.v1.ManagerService/FinishRestore"
)

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerServiceClient interface {
	NotifyCheckpoint(ctx context.Context, in *NotifyCheckpointRequest, opts ...grpc.CallOption) (*NotifyCheckpointResponse, error)
	RequestMigrationRestore(ctx context.Context, in *MigrationRestoreRequest, opts ...grpc.CallOption) (*MigrationRestoreResponse, error)
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullImageResponse], error)
	FinishRestore(ctx context.Context, in *FinishRestoreRequest, opts ...grpc.CallOption) (*FinishRestoreResponse, error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) NotifyCheckpoint(ctx context.Context, in *NotifyCheckpointRequest, opts ...grpc.CallOption) (*NotifyCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyCheckpointResponse)
	err := c.cc.Invoke(ctx, ManagerService_NotifyCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RequestMigrationRestore(ctx context.Context, in *MigrationRestoreRequest, opts ...grpc.CallOption) (*MigrationRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationRestoreResponse)
	err := c.cc.Invoke(ctx, ManagerService_RequestMigrationRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagerService_ServiceDesc.Streams[0], ManagerService_PullImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullImageRequest, PullImageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_PullImageClient = grpc.ServerStreamingClient[PullImageResponse]

func (c *managerServiceClient) FinishRestore(ctx context.Context, in *FinishRestoreRequest, opts ...grpc.CallOption) (*FinishRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRestoreResponse)
	err := c.cc.Invoke(ctx, ManagerService_FinishRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
// All implementations must embed UnimplementedManagerServiceServer
// for forward compatibility.
type ManagerServiceServer interface {
	NotifyCheckpoint(context.Context, *NotifyCheckpointRequest) (*NotifyCheckpointResponse, error)
	RequestMigrationRestore(context.Context, *MigrationRestoreRequest) (*MigrationRestoreResponse, error)
	PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullImageResponse]) error
	FinishRestore(context.Context, *FinishRestoreRequest) (*FinishRestoreResponse, error)
	mustEmbedUnimplementedManagerServiceServer()
}

// UnimplementedManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServiceServer struct{}

func (UnimplementedManagerServiceServer) NotifyCheckpoint(context.Context, *NotifyCheckpointRequest) (*NotifyCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyCheckpoint not implemented")
}
func (UnimplementedManagerServiceServer) RequestMigrationRestore(context.Context, *MigrationRestoreRequest) (*MigrationRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMigrationRestore not implemented")
}
func (UnimplementedManagerServiceServer) PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullImageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedManagerServiceServer) FinishRestore(context.Context, *FinishRestoreRequest) (*FinishRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRestore not implemented")
}
func (UnimplementedManagerServiceServer) mustEmbedUnimplementedManagerServiceServer() {}
func (UnimplementedManagerServiceServer) testEmbeddedByValue()                        {}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_NotifyCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).NotifyCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_NotifyCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).NotifyCheckpoint(ctx, req.(*NotifyCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RequestMigrationRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RequestMigrationRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_RequestMigrationRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RequestMigrationRestore(ctx, req.(*MigrationRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServiceServer).PullImage(m, &grpc.GenericServerStream[PullImageRequest, PullImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_PullImageServer = grpc.ServerStreamingServer[PullImageResponse]

func _ManagerService_FinishRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).FinishRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_FinishRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).FinishRestore(ctx, req.(*FinishRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shiftpod.manager.v1.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyCheckpoint",
			Handler:    _ManagerService_NotifyCheckpoint_Handler,
		},
		{
			MethodName: "RequestMigrationRestore",
			Handler:    _ManagerService_RequestMigrationRestore_Handler,
		},
		{
			MethodName: "FinishRestore",
			Handler:    _ManagerService_FinishRestore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullImage",
			Handler:       _ManagerService_PullImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/manager.proto",
}
