// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: proto/manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyCheckpointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerId    string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	CheckpointPath string                 `protobuf:"bytes,2,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"`
	PodInfo        *PodInfo               `protobuf:"bytes,3,opt,name=pod_info,json=podInfo,proto3" json:"pod_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyCheckpointRequest) Reset() {
	*x = NotifyCheckpointRequest{}
	mi := &file_proto_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyCheckpointRequest) ProtoMessage() {}

func (x *NotifyCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyCheckpointRequest.ProtoReflect.Descriptor instead.
func (*NotifyCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyCheckpointRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *NotifyCheckpointRequest) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

func (x *NotifyCheckpointRequest) GetPodInfo() *PodInfo {
	if x != nil {
		return x.PodInfo
	}
	return nil
}

type NotifyCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyCheckpointResponse) Reset() {
	*x = NotifyCheckpointResponse{}
	mi := &file_proto_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyCheckpointResponse) ProtoMessage() {}

func (x *NotifyCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyCheckpointResponse.ProtoReflect.Descriptor instead.
func (*NotifyCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{1}
}

type MigrationRestoreRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PodTemplateHash string                 `protobuf:"bytes,1,opt,name=pod_template_hash,json=podTemplateHash,proto3" json:"pod_template_hash,omitempty"`
	PodName         string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName   string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MigrationRestoreRequest) Reset() {
	*x = MigrationRestoreRequest{}
	mi := &file_proto_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRestoreRequest) ProtoMessage() {}

func (x *MigrationRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRestoreRequest.ProtoReflect.Descriptor instead.
func (*MigrationRestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{2}
}

func (x *MigrationRestoreRequest) GetPodTemplateHash() string {
	if x != nil {
		return x.PodTemplateHash
	}
	return ""
}

func (x *MigrationRestoreRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *MigrationRestoreRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type MigrationRestoreResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Found          bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	CheckpointPath string                 `protobuf:"bytes,2,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrationRestoreResponse) Reset() {
	*x = MigrationRestoreResponse{}
	mi := &file_proto_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationRestoreResponse) ProtoMessage() {}

func (x *MigrationRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationRestoreResponse.ProtoReflect.Descriptor instead.
func (*MigrationRestoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{3}
}

func (x *MigrationRestoreResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *MigrationRestoreResponse) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

type PullImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CheckpointPath string                 `protobuf:"bytes,1,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullImageRequest) Reset() {
	*x = PullImageRequest{}
	mi := &file_proto_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageRequest) ProtoMessage() {}

func (x *PullImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageRequest.ProtoReflect.Descriptor instead.
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{4}
}

func (x *PullImageRequest) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

type PullImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageResponse) Reset() {
	*x = PullImageResponse{}
	mi := &file_proto_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageResponse) ProtoMessage() {}

func (x *PullImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageResponse.ProtoReflect.Descriptor instead.
func (*PullImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{5}
}

func (x *PullImageResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type FinishRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRestoreRequest) Reset() {
	*x = FinishRestoreRequest{}
	mi := &file_proto_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRestoreRequest) ProtoMessage() {}

func (x *FinishRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRestoreRequest.ProtoReflect.Descriptor instead.
func (*FinishRestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{6}
}

func (x *FinishRestoreRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *FinishRestoreRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FinishRestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRestoreResponse) Reset() {
	*x = FinishRestoreResponse{}
	mi := &file_proto_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRestoreResponse) ProtoMessage() {}

func (x *FinishRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRestoreResponse.ProtoReflect.Descriptor instead.
func (*FinishRestoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{7}
}

type PodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	TemplateHash  string                 `protobuf:"bytes,4,opt,name=template_hash,json=templateHash,proto3" json:"template_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	mi := &file_proto_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{8}
}

func (x *PodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodInfo) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *PodInfo) GetTemplateHash() string {
	if x != nil {
		return x.TemplateHash
	}
	return ""
}

var File_proto_manager_proto protoreflect.FileDescriptor

const file_proto_manager_proto_rawDesc = "" +
	"\n" +
	"\x13proto/manager.proto\x12\x13shiftpod.manager.v1\"\x9e\x01\n" +
	"\x17NotifyCheckpointRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12'\n" +
	"\x0fcheckpoint_path\x18\x02 \x01(\tR\x0echeckpointPath\x127\n" +
	"\bpod_info\x18\x03 \x01(\v2\x1c.shiftpod.manager.v1.PodInfoR\apodInfo\"\x1a\n" +
	"\x18NotifyCheckpointResponse\"\x87\x01\n" +
	"\x17MigrationRestoreRequest\x12*\n" +
	"\x11pod_template_hash\x18\x01 \x01(\tR\x0fpodTemplateHash\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\"Y\n" +
	"\x18MigrationRestoreResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12'\n" +
	"\x0fcheckpoint_path\x18\x02 \x01(\tR\x0echeckpointPath\";\n" +
	"\x10PullImageRequest\x12'\n" +
	"\x0fcheckpoint_path\x18\x01 \x01(\tR\x0echeckpointPath\")\n" +
	"\x11PullImageResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"S\n" +
	"\x14FinishRestoreRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x17\n" +
	"\x15FinishRestoreResponse\"\x87\x01\n" +
	"\aPodInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12#\n" +
	"\rtemplate_hash\x18\x04 \x01(\tR\ftemplateHash2\xbf\x03\n" +
	"\x0eManagerService\x12o\n" +
	"\x10NotifyCheckpoint\x12,.shiftpod.manager.v1.NotifyCheckpointRequest\x1a-.shiftpod.manager.v1.NotifyCheckpointResponse\x12v\n" +
	"\x17RequestMigrationRestore\x12,.shiftpod.manager.v1.MigrationRestoreRequest\x1a-.shiftpod.manager.v1.MigrationRestoreResponse\x12\\\n" +
	"\tPullImage\x12%.shiftpod.manager.v1.PullImageRequest\x1a&.shiftpod.manager.v1.PullImageResponse0\x01\x12f\n" +
	"\rFinishRestore\x12).shiftpod.manager.v1.FinishRestoreRequest\x1a*.shiftpod.manager.v1.FinishRestoreResponseB#Z!github.com/kelvinc/shiftpod/protob\x06proto3"

var (
	file_proto_manager_proto_rawDescOnce sync.Once
	file_proto_manager_proto_rawDescData []byte
)

func file_proto_manager_proto_rawDescGZIP() []byte {
	file_proto_manager_proto_rawDescOnce.Do(func() {
		file_proto_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)))
	})
	return file_proto_manager_proto_rawDescData
}

var file_proto_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_manager_proto_goTypes = []any{
	(*NotifyCheckpointRequest)(nil),  // 0: shiftpod.manager.v1.NotifyCheckpointRequest
	(*NotifyCheckpointResponse)(nil), // 1: shiftpod.manager.v1.NotifyCheckpointResponse
	(*MigrationRestoreRequest)(nil),  // 2: shiftpod.manager.v1.MigrationRestoreRequest
	(*MigrationRestoreResponse)(nil), // 3: shiftpod.manager.v1.MigrationRestoreResponse
	(*PullImageRequest)(nil),         // 4: shiftpod.manager.v1.PullImageRequest
	(*PullImageResponse)(nil),        // 5: shiftpod.manager.v1.PullImageResponse
	(*FinishRestoreRequest)(nil),     // 6: shiftpod.manager.v1.FinishRestoreRequest
	(*FinishRestoreResponse)(nil),    // 7: shiftpod.manager.v1.FinishRestoreResponse
	(*PodInfo)(nil),                  // 8: shiftpod.manager.v1.PodInfo
}
var file_proto_manager_proto_depIdxs = []int32{
	8, // 0: shiftpod.manager.v1.NotifyCheckpointRequest.pod_info:type_name -> shiftpod.manager.v1.PodInfo
	0, // 1: shiftpod.manager.v1.ManagerService.NotifyCheckpoint:input_type -> shiftpod.manager.v1.NotifyCheckpointRequest
	2, // 2: shiftpod.manager.v1.ManagerService.RequestMigrationRestore:input_type -> shiftpod.manager.v1.MigrationRestoreRequest
	4, // 3: shiftpod.manager.v1.ManagerService.PullImage:input_type -> shiftpod.manager.v1.PullImageRequest
	6, // 4: shiftpod.manager.v1.ManagerService.FinishRestore:input_type -> shiftpod.manager.v1.FinishRestoreRequest
	1, // 5: shiftpod.manager.v1.ManagerService.NotifyCheckpoint:output_type -> shiftpod.manager.v1.NotifyCheckpointResponse
	3, // 6: shiftpod.manager.v1.ManagerService.RequestMigrationRestore:output_type -> shiftpod.manager.v1.MigrationRestoreResponse
	5, // 7: shiftpod.manager.v1.ManagerService.PullImage:output_type -> shiftpod.manager.v1.PullImageResponse
	7, // 8: shiftpod.manager.v1.ManagerService.FinishRestore:output_type -> shiftpod.manager.v1.FinishRestoreResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_manager_proto_init() }
func file_proto_manager_proto_init() {
	if File_proto_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manager_proto_goTypes,
		DependencyIndexes: file_proto_manager_proto_depIdxs,
		MessageInfos:      file_proto_manager_proto_msgTypes,
	}.Build()
	File_proto_manager_proto = out.File
	file_proto_manager_proto_goTypes = nil
	file_proto_manager_proto_depIdxs = nil
}
